allowBuilds:
  '@codemirror/autocomplete@https://codeload.github.com/overleaf/codemirror-autocomplete/tar.gz/2aff95fc5d6cda311537ed62066c9a0afbbbcad8': true
  '@parcel/watcher': false
  esbuild: false
  unrs-resolver: false

overrides:
  rdyjs: 13.6.33
  rdy-protocols: 1.0.14
  rdlib0: 0.2.106
  react: 18.2.0
  react-dom: 18.2.0
  react-redux: 9.2.0
  redux: 5.0.1
