allowBuilds:
  '@codemirror/autocomplete@https://codeload.github.com/overleaf/codemirror-autocomplete/tar.gz/2aff95fc5d6cda311537ed62066c9a0afbbbcad8': true
  '@parcel/watcher': set this to true or false
  esbuild: set this to true or false
  unrs-resolver: set this to true or false
