name: tex-web-pro

on:
  push:
    branches: [ main, feature/* ]

jobs:
  call-build:
    uses: RedDwarfTech/rd-workflow/.github/workflows/web-app-publish-k8s.yml@main
    with:
      target: stage
      node-version: 20
      app-namespace: reddwarf-pro
      app-name: texhub-web
