name: Rollback by Tag
on:
  workflow_dispatch:
    inputs:
      tag:
        description: '要回滚的 Git Tag (例如 v1.2.3)'
        required: true
        type: string

jobs:
  call-build:
    uses: RedDwarfTech/rd-workflow/.github/workflows/web-app-publish-k8s.yml@main
    secrets: inherit
    with:
      target: stage
      node-version: 20
      app-namespace: reddwarf-pro
      app-name: texhub-web
      app-tag: ${{ github.event.inputs.tag }}