name: Rollback by Tag
on:
  workflow_dispatch:
    inputs:
      tag:
        description: '要回滚的 Git Tag (例如 v1.2.3)'
        required: true
        type: string

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Check tag code
        uses: actions/checkout@v4
        with:
          ref: refs/tags/${{ github.event.inputs.tag }}
          fetch-depth: 0

      - name: Get tag info
        id: tag-info
        run: |
          echo "TAG=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          echo "COMMIT=$(git rev-parse ${{ github.event.inputs.tag }})" >> $GITHUB_OUTPUT

      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Build React App
        run: |
          npm install
          npm run build
        env:
          CI: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}
          username: ${{ secrets.ALIYUN_DOCKER_REPO_USER_NAME }}
          password: ${{ secrets.ALIYUN_DOCKER_REPO_USER_PASSWORD }}

      - name: Build image push to aliyun
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}/reddwarf-pro/texhub-web:${{ github.sha }} 
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: Dockerfile
          push: true
    
        # https://github.com/steebchen/kubectl
      - name: deploy to cluster
        uses: steebchen/kubectl@v2.0.0
        with: # defaults to latest kubectl binary version
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: set image --record deployment/texhub-web texhub-web=registry.cn-hongkong.aliyuncs.com/reddwarf-pro/texhub-web:${{ github.sha }} -n reddwarf-pro

      - name: verify deployment
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          version: v1.21.0 # specify kubectl binary version explicitly
          command: rollout status deployment/texhub-web -n reddwarf-pro